# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/sensors.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/sensors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/sensors.proto\x12\x07sensors\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\rSensorRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"b\n\rSensorReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x14\n\x0creading_type\x18\x02 \x01(\t\x12\x15\n\rreading_value\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"8\n\rSensorHistory\x12\'\n\x07history\x18\x01 \x03(\x0b\x32\x16.sensors.SensorReading\"!\n\x0bSensorsList\x12\x12\n\nsensor_ids\x18\x01 \x03(\t\"J\n\x0b\x41lertStatus\x12\x11\n\ttriggered\x18\x01 \x01(\x08\x12\x15\n\ralert_message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"1\n\tAlertList\x12$\n\x06\x61lerts\x18\x01 \x03(\x0b\x32\x14.sensors.AlertStatus\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc7\x01\n\rSensorManager\x12?\n\rGetSensorData\x12\x16.sensors.SensorRequest\x1a\x16.sensors.SensorReading\x12;\n\x0bListSensors\x12\x16.google.protobuf.Empty\x1a\x14.sensors.SensorsList\x12\x38\n\x0bPushReading\x12\x16.sensors.SensorReading\x1a\x11.sensors.Response2\x88\x01\n\x0eStorageService\x12\x38\n\x0bSaveReading\x12\x16.sensors.SensorReading\x1a\x11.sensors.Response\x12<\n\nGetHistory\x12\x16.sensors.SensorRequest\x1a\x16.sensors.SensorHistory2\x83\x01\n\x0c\x41lertService\x12:\n\nCheckAlert\x12\x16.sensors.SensorReading\x1a\x14.sensors.AlertStatus\x12\x37\n\tGetAlerts\x12\x16.google.protobuf.Empty\x1a\x12.sensors.AlertListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.sensors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREQUEST']._serialized_start=62
  _globals['_SENSORREQUEST']._serialized_end=96
  _globals['_SENSORREADING']._serialized_start=98
  _globals['_SENSORREADING']._serialized_end=196
  _globals['_SENSORHISTORY']._serialized_start=198
  _globals['_SENSORHISTORY']._serialized_end=254
  _globals['_SENSORSLIST']._serialized_start=256
  _globals['_SENSORSLIST']._serialized_end=289
  _globals['_ALERTSTATUS']._serialized_start=291
  _globals['_ALERTSTATUS']._serialized_end=365
  _globals['_ALERTLIST']._serialized_start=367
  _globals['_ALERTLIST']._serialized_end=416
  _globals['_RESPONSE']._serialized_start=418
  _globals['_RESPONSE']._serialized_end=444
  _globals['_SENSORMANAGER']._serialized_start=447
  _globals['_SENSORMANAGER']._serialized_end=646
  _globals['_STORAGESERVICE']._serialized_start=649
  _globals['_STORAGESERVICE']._serialized_end=785
  _globals['_ALERTSERVICE']._serialized_start=788
  _globals['_ALERTSERVICE']._serialized_end=919
# @@protoc_insertion_point(module_scope)
